"""empty message

Revision ID: 34d2a0d0acdf
Revises: 
Create Date: 2017-01-22 15:32:32.704248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d2a0d0acdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('visitdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_sid'), 'students', ['sid'], unique=True)
    op.create_index(op.f('ix_students_visitdate'), 'students', ['visitdate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_visitdate'), table_name='students')
    op.drop_index(op.f('ix_students_sid'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
