"""empty message

Revision ID: 39c9678b7c40
Revises: 34d2a0d0acdf
Create Date: 2017-01-25 20:46:43.862268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39c9678b7c40'
down_revision = '34d2a0d0acdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('visitdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_name'), 'visits', ['name'], unique=False)
    op.create_index(op.f('ix_visits_sid'), 'visits', ['sid'], unique=True)
    op.create_index(op.f('ix_visits_visitdate'), 'visits', ['visitdate'], unique=False)
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('visitdate', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_visits_visitdate'), table_name='visits')
    op.drop_index(op.f('ix_visits_sid'), table_name='visits')
    op.drop_index(op.f('ix_visits_name'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
