"""empty message

Revision ID: a03394749fad
Revises: 39c9678b7c40
Create Date: 2017-01-26 14:07:26.827091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03394749fad'
down_revision = '39c9678b7c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visits_sid', table_name='visits')
    op.create_index(op.f('ix_visits_sid'), 'visits', ['sid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_sid'), table_name='visits')
    op.create_index('ix_visits_sid', 'visits', ['sid'], unique=True)
    # ### end Alembic commands ###
